### ISSUE TITLE
tinyGL

### ISSUE THREAD

**Issue by lm8** [C-Chads/C-Chads#2] opened 2021-06-07 14:59 UTC
Someone recently told me about your tinyGL project.  It's nice to see active development for tinyGL.  I've been using PicoGL which is a fork of tinyGL for several years.  I've added features from several other tinyGL forks along with my own modifications.  It's interesting comparing what you've fixed with what I've added.  I have some functionality for depth, alpha and logical operators along with several other additions.  I've been using picoGL with Emilia pinball and am trying to work on getting the rendering a little closer to what OpenGL displays.  I also ported a Qubix game to use it.  The lines don't appear to be rendering as straight as I'd like though.  Was wondering if you've done any patching to make drawing the ends of lines more accurate.  Not sure if there's much code that could be shared between your project and mine because they seem to have diverged quite a bit even though the base was tinyGL at one point in time.  It's nice seeing someone else working on this though since there are so few projects actively using tinyGL forks.  Look forward to trying out some of your demo programs and seeing how they work with PicoGL.

**Comment by gek169** [comment] 2021-06-07 17:43
There were numerous graphical bugs in the rendering of lines and edges of triangles that I fixed in this library (Some of which are still visible in the gifs on the repo's front)
Notably:
* Poor color interpolation to white or black (black goes to white and white goes to black due to errors in the fixed point representation)
* Aliasing errors

That said, TinyGL does not aim to be a reference implementation. you won't get pixel-perfect reproduction of OpenGL renders.

I'm not sure why you'd have lines that weren't rendering straight. TinyGL uses DDA and while I did find some bugs in his algorithm I never saw lines that were anything but perfectly straight.
The demo programs use features that i've added to TinyGL, they likely will not work with PicoGL. All demos use the text renderer that i've added, for example.

You should ntoe The build process for the library has changed. By default, only the raw demos build (I figure those are the least likely to fail). You have to explicitly `make SDL_Examples` to build the interactive demos.

Thanks, please tell me if you find use in the project. I may be able to help you with integration.

**Comment by lm8** [comment] 2021-06-08 12:25
There were a couple of bugs with rendering that I didn't notice until I had specific situations that tested them.  The Quibix program draws grids and then rotates them around an axis.  That's when I noticed some strange effects in the line drawing.  Also noticed that the original TInyGL texture mapping was off by at least a pixel.  You've made several changes, so you may have already addressed that.  I fixed the issue I found when I added dynamic power of 2 texture size support.  I wrote about some of the bugs at one point when I was working on them because I knew I'd forget the details at a later date:  https://lmemsm.dreamwidth.org/tag/picogl  Switching demos from different forks of TinyGL or even moving some OpenGL examples to TinyGL forks isn't that difficult.  Many are fairly easy to port.  I haven't added text rendering to what I'm using, but I added enough support to handle font atlases and I've used that in conjunction with the freetype library to render TrueType fonts.  Felt that was sufficient for my needs in terms of text rendering.  If I have some free time, I may try porting Quibix to your version of TinyGL and see if the line issue is resolved or not.  It's nice seeing some active development on TinyGL again.

**Comment by gek169** [comment] 2021-06-09 06:54
My main reasoning for not adding dynamic power-of-two texture support is the lack of optimization that the compiler will be able to perform unrolling loops. I could add it, but it would probably reduce the speed of the renderer.
If you really need high resolution textures i'd say bump up the size to your maximum needed size and roll with it. You get an increased cache miss rate for larger texture sizes but it seems to be manageable.


If you've implemented the ARB extensions for point sprite scaling or smoothing, please tell me. Those are on my TODO. Antialiasing is also on my TODO. I'm unsure if I want to pursue alpha blending, but I might (The idea being that we could run quake 3 arena or something with tgl)

"Also noticed that the original TInyGL texture mapping was off by at least a pixel."
This is a bug i have not *specifically* encountered in the library. My guess, though, is that this is due to the old 16 bit precision fixed point format that Bellard wrote for texture coordinates, which has been improved (And de-obfuscated to some extent. I tried to make it readable... but Bellard's coding style... you know how it is. He's a *mad* genius. Mad as in crazy.)

I'm glad to get in touch with the maintainer of another TinyGL fork. I'd love to hear about what you've discovered in the library, I've tried very hard to run the library through test cases to spot bugs, and I've found a lot of them. A lot of memory leaks especially but I found quite a bit of implicit Undefined Behavior usage. 
~~~~~~~~~~~~~~~~~~~
From reading your web-page
~~~~~~~~~~~~~~~~~~~
"I'm currently working on refactoring the texture related code and cleaning up how to handle conversions between different formats (such as RGB, RGBA, BGRA)"
There's a nasty bug that I found in TinyGL. Different formats for color are used for the per-vertex color and for the textured triangles. Additionally, there's an endianness issue.

as for converting from user data to internal representation, bellard already wrote almost everything you'll need in image_util.c.
Converting between formats with the same numbers of BPC is of course trivial (God forbid you discover someone using 5G6B5R)

My recommendation purely for maintainability and minimalism is to remove support for anything other than 16 bit or 32 bit. paletted 256 color and 24 bit color are not worth it.
24 bit color runs slower than 32 bit color on every single platform I run tests on. 256 color palette'd might be interesting for MS-DOS, but the segmented memory model prevents TinyGL from running on it. Ultimately if people want a paletted output, they probably won't rely on TinyGL's 8bpp implementation.

There are a bunch of quite insidious bugs in how interpolation is done in vertex processing which cause errors, the precision errors I mentioned before, and out-of-range errors (They cause, for instance, the white outlines in the gifs on the front of this repository. I fixed that bug, but I haven't updated the gifs.)

I documented many of the bugs I encountered while fixing up the library on the front of this repository.

**Comment by gek169** [comment] 2021-06-09 06:56
I did not implement a "serious" text renderer, it's a quick and dirty debug bitmap font.

I figure it's perfect for games and apps that need something that "just works" to print some information to the screen. It'd work for making a graphical shell for a system without a REPL.

**Comment by gek169** [comment] 2021-08-06 16:34
Closing this due to inactivity. Feel free to open a new one on the tinygl repository if you would like to continue this thread.

**Closed as completed by gek169** 2021-08-06 16:34 UTC
